name: Latest blog post workflow

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          gh_token: ${{ GITHUB.TOKEN }}
          # Maximum number of posts you want to show on your readme, all feeds combined
          max_post_count: 6
          # Comma separated list of RSS feed urls
          feed_list: "https://www.griefed.de/Blog/feed"
          # Inserts newline before the closing tag and after the opening tag when using the template option, for formatting
          tag_post_pre_newline: true
          # Allows you to change the format of the date or time displayed when using the $date in the template option
          date_format: GMT:dddd, D MMMM YYYY, hh:mm Zz
          # Allows you to trim the description in the posts list
          description_max_length: 20
