name: Update README with blog posts and sponsors

on:
  workflow_dispatch:

jobs:
  blog:
    runs-on: ubuntu-latest
    name: Fetch and Generate Blog Posts
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate
        uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://blog.griefed.de/feed'
          file: 'README.md'
          format: '<div align="center">${monthshort} ${02day} - <a href="${url}">${title}</a></div>'

      - name: Add GitHub Sponsors to Readme
        uses: JamesIves/github-sponsors-readme-action@v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List
        run: pwd && ls -ahl

      - name: Push
        run: |
          apt-get update && apt-get install git -y && \
          git config --global user.name ${{ secrets.GIT_USER }} && \
          git config --global user.email ${{ secrets.GIT_MAIL }} && \
          git add README.md && \
          wait && \
          git commit -m 'Update fancy schmancy blog posts and sponsors' && \
          git push "https://${{ secrets.GIT_USER }}:${{ secrets.GITLAB_TOKEN }}@${{ secrets.CI_SERVER_HOST }}/${{ secrets.CI_PROJECT_PATH }}.git" --all

#      - name: Push
#        uses: actions-go/push@master
#        with:
#          commit-message: 'Update README'
#          remote: origin